//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Res/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""KeyBoardAndMouse"",
            ""id"": ""0ccbb664-d4cd-450c-87f2-d5498244dbe8"",
            ""actions"": [
                {
                    ""name"": ""MoveMent"",
                    ""type"": ""Value"",
                    ""id"": ""07fec60c-d5ca-4676-a008-a95e6ae3d81d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bdf67c28-c88b-42ee-9ecf-d3bd3c5ad322"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMent"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ca72a4b-1d49-49b4-8d9e-9e81d4a14818"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""58b1a191-cfcf-410f-a19b-219237ae26fc"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8d397e28-87c2-470c-8937-16c89e27ffdd"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8e473fb3-6cd6-43bb-a87b-7ec93b2f4bd1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveMent"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KeyBoardAndMouse
        m_KeyBoardAndMouse = asset.FindActionMap("KeyBoardAndMouse", throwIfNotFound: true);
        m_KeyBoardAndMouse_MoveMent = m_KeyBoardAndMouse.FindAction("MoveMent", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyBoardAndMouse
    private readonly InputActionMap m_KeyBoardAndMouse;
    private List<IKeyBoardAndMouseActions> m_KeyBoardAndMouseActionsCallbackInterfaces = new List<IKeyBoardAndMouseActions>();
    private readonly InputAction m_KeyBoardAndMouse_MoveMent;
    public struct KeyBoardAndMouseActions
    {
        private @PlayerInputAction m_Wrapper;
        public KeyBoardAndMouseActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveMent => m_Wrapper.m_KeyBoardAndMouse_MoveMent;
        public InputActionMap Get() { return m_Wrapper.m_KeyBoardAndMouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyBoardAndMouseActions set) { return set.Get(); }
        public void AddCallbacks(IKeyBoardAndMouseActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Add(instance);
            @MoveMent.started += instance.OnMoveMent;
            @MoveMent.performed += instance.OnMoveMent;
            @MoveMent.canceled += instance.OnMoveMent;
        }

        private void UnregisterCallbacks(IKeyBoardAndMouseActions instance)
        {
            @MoveMent.started -= instance.OnMoveMent;
            @MoveMent.performed -= instance.OnMoveMent;
            @MoveMent.canceled -= instance.OnMoveMent;
        }

        public void RemoveCallbacks(IKeyBoardAndMouseActions instance)
        {
            if (m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyBoardAndMouseActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyBoardAndMouseActions @KeyBoardAndMouse => new KeyBoardAndMouseActions(this);
    public interface IKeyBoardAndMouseActions
    {
        void OnMoveMent(InputAction.CallbackContext context);
    }
}
